services:
  backend:
    build: ./app
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cms
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_MONGODB_URI=mongodb://user:pass@mongodb:27017/prescriptions
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cms
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_db:/data/db
volumes:
  mysql_db:
  mongo_db: