name: Frontend Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install -g eslint stylelint htmlhint
      - name: Run ESLint
        run: eslint app/src/main/resources/static/assets/js//*.js || true
      - name: Run Stylelint
        run: stylelint 'app/src/main/resources/static/css/**/*.css' || true
      - name: Run HTMLHint
        run: htmlhint 'app/src/main/resources/templates/**/*.html' || true
